spring:
  application:
    name: week4

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jwt:
    secret: ${JWT_SECRET}

  logging:
    level:
      org.hibernate.orm.jdbc.bind: trace

file:
  profile-upload-dir: ${user.home}/dev-uploads/ProfileImage
  post-upload-dir: ${user.home}/dev-uploads/PostImage

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_S3_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}
